{
 "title": "All weather stations",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "Eaunes" }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <font size=\"+5\"><b>ALL WEATHER STATIONS</b></font>\n  <hr>\n  <br>\n  <br>\n  <img src=\"/public/img/MeteoFox_logo.png\" width=\"150\">\n</div>"
   }
  },
  { "title": "Summary", "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Software version" ], "type": "alias" }
      ],
      [
       { "params": [ "time_last_communication" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1000" ], "type": "math" },
       { "params": [ "Last communication" ], "type": "alias" }
      ],
      [
       { "params": [ "time_last_startup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Last startup" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reset flags" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weather data",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "tamb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "hamb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "light" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "UV index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "uv_index" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Absolute pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "patm_abs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Le_Vigan" }
     ]
    }
   ]
  },
  {
   "title": "Sea-level pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "patm_sea" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Le_Vigan" }
     ]
    }
   ]
  },
  {
   "title": "Peak wind speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_peak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Average wind speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_avrg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wdir_avrg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Geoloc data",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Geoloc",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "altitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "GPS fix duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "gps_fix_duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Monitoring data",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "PCB temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "tpcb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "PCB humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "hpcb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "MCU temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "tmcu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "MCU voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vmcu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Solar cell voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vsrc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  },
  {
   "title": "Supercap voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vcap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "!=", "value": "Proto_HW1.0" },
      { "condition": "AND", "key": "site", "operator": "!=", "value": "Proto_HW2.0" }
     ]
    }
   ]
  }
 ]
}