{
 "title": "Le Lien (65)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "site", "query": "Le_Lien" }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <font size=\"+5\"><b>LE LIEN</b></font>\n  <hr>\n  <br>\n  <br>\n  <img src=\"/public/img/MeteoFox_logo.png\" width=\"150\">\n</div>"
   }
  },
  {
   "title": "Commissioning: 20xx-xx-xx",
   "type": "text",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<br>\n<div class=\"text-center dashboard-header\">\n  <img src=\"/public/img/Le_Lien_1.jpg\" height=\"270\" align=\"middle\">\n</div>"
   }
  },
  {
   "title": "Last startup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "time_last_startup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Last communication",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "time_last_communication" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Software version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } } },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "tamb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "hamb" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "hamb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "hamb" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "hamb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "patm_sea" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "patm_sea" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "patm_sea" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "patm_sea" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "wspd_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "wspd_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "wspd_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_peak" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "wspd_peak" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "wspd_peak" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "wspd_peak" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wdir_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "*0-1" ], "type": "math" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "wdir_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*0-1" ], "type": "math" },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "wdir_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*0-1" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "wdir_avrg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Weather data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last message",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "time_last_weather_data" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "tamb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "hamb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "light" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "UV index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "uv_index" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Absolute pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "patm_abs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Sea-level pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "patm_sea" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "Average",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_avrg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    },
    {
     "alias": "Peak",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_peak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind rose",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wdir_avrg" ], "type": "field" }
      ],
      [
       { "params": [ "wspd_peak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wdir_avrg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "For last 24h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_site",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "For current time range",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_site",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Geoloc data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last message",
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "time_last_geoloc_data" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Geoloc",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 67 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "altitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 5, "x": 14, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_site",
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS fix duration",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_site",
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "gps_fix_duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Monitoring data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last message",
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "time_last_monitoring_data" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "PCB temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "tpcb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "PCB humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "hpcb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "MCU temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "tmcu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "MCU voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vmcu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Solar cell voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vsrc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Supercap voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vcap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Status bits",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&128 / 128" ], "type": "math" },
       { "params": [ "Daily downlink" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&64 / 64" ], "type": "math" },
       { "params": [ "Daily geoloc" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&32 / 32" ], "type": "math" },
       { "params": [ "Daily RTC calibration" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&16 / 16" ], "type": "math" },
       { "params": [ "First RTC calibration" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&8 / 8" ], "type": "math" },
       { "params": [ "LSE status" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&4 /4" ], "type": "math" },
       { "params": [ "LSI status" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&2 / 2" ], "type": "math" },
       { "params": [ "MCU clock source" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&1 / 1" ], "type": "math" },
       { "params": [ "Station mode" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Reset flags",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "measurement": "global",
     "select": [
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&128 / 128" ], "type": "math" },
       { "params": [ "Low power" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&64 / 64" ], "type": "math" },
       { "params": [ "Window watchdog" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&32 / 32" ], "type": "math" },
       { "params": [ "Independent watchdog" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&16 / 16" ], "type": "math" },
       { "params": [ "Software" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&8 / 8" ], "type": "math" },
       { "params": [ "POR" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&4 /4" ], "type": "math" },
       { "params": [ "Pin" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&2 / 2" ], "type": "math" },
       { "params": [ "Option bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&1 / 1" ], "type": "math" },
       { "params": [ "Firewall" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Error stack",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "targets": [
    {
     "measurement": "global",
     "select": [
      [
       { "params": [ "error" ], "type": "field" },
       { "params": [ "Error code" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  }
 ]
}