"""
* sigfox.py
*
*  Created on: 08 sep. 2024
*      Author: Ludo
"""

### SIGFOX MACROS ###

# Sigfox callback types.
SIGFOX_CALLBACK_TYPE_DATA_BIDIR = "data_bidir"
SIGFOX_CALLBACK_TYPE_DATA_ADVANCED = "data_advanced"
SIGFOX_CALLBACK_TYPE_SERVICE_STATUS = "service_status"
SIGFOX_CALLBACK_TYPE_SERVICE_ACKNOWLEDGE = "service_acknowledge"

# Sigfox callbacks fields.
SIGFOX_CALLBACK_JSON_KEY_TYPE = "type"
SIGFOX_CALLBACK_JSON_KEY_TIME = "time"
SIGFOX_CALLBACK_JSON_KEY_EP_ID = "ep_id"
SIGFOX_CALLBACK_JSON_KEY_MESSAGE_COUNTER = "message_counter"
SIGFOX_CALLBACK_JSON_KEY_UL_PAYLOAD = "ul_payload"
SIGFOX_CALLBACK_JSON_KEY_BIDIRECTIONAL_FLAG = "bidirectional_flag"
SIGFOX_CALLBACK_JSON_KEY_GEOLOCATION = "geolocation"
SIGFOX_CALLBACK_JSON_KEY_GEOLOCATION_LATITUDE = "lat"
SIGFOX_CALLBACK_JSON_KEY_GEOLOCATION_LONGITUDE = "lng"
SIGFOX_CALLBACK_JSON_KEY_GEOLOCATION_RADIUS = "radius"
SIGFOX_CALLBACK_JSON_KEY_GEOLOCATION_SOURCE = "source"
SIGFOX_CALLBACK_JSON_KEY_GEOLOCATION_STATUS = "status"
SIGFOX_CALLBACK_JSON_KEY_DL_PAYLOAD = "dl_payload"
SIGFOX_CALLBACK_JSON_KEY_DL_SUCCESS = "dl_success"
SIGFOX_CALLBACK_JSON_KEY_DL_STATUS = "dl_status"
SIGFOX_CALLBACK_JSON_TRUE = "true"
SIGFOX_CALLBACK_JSON_FALSE = "false"

SIGFOX_CALLBACK_GEOLOCATION_SOURCE_GPS = 1
SIGFOX_CALLBACK_GEOLOCATION_SOURCE_NETWORK = 2
SIGFOX_CALLBACK_GEOLOCATION_SOURCE_WIFI = 6

SIGFOX_CALLBACK_GEOLOCATION_STATUS_NO_POSITION = 0
SIGFOX_CALLBACK_GEOLOCATION_STATUS_OK = 1
SIGFOX_CALLBACK_GEOLOCATION_STATUS_FALLBACK_OR_WIFI = 2
SIGFOX_CALLBACK_GEOLOCATION_STATUS_INVALID_PAYLOAD = 3
