{
 "title": "Voiture",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "asset", "query": "Car" }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <font size=\"+5\"><b>VOITURE</b></font>\n  <hr>\n  <br>\n  <br>\n  <img src=\"/public/img/TrackFox_logo.png\" width=\"150\">\n</div>"
   }
  },
  {
   "title": "Last startup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "time_last_startup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Last communication",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "time_last_communication" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Software version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Geoloc data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last message",
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "time_last_geoloc_data" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Track map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Last GPS points",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "asset" ], "type": "tag" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       { "params": [ "Latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       { "params": [ "Longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "altitude" ], "type": "field" },
       { "params": [ "Altitude" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Timeline",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "geoloc",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" },
       { "params": [ " *0" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    },
    {
     "alias": "Peak",
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wspd_peak" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Monitoring data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last message",
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "time_last_monitoring_data" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "tamb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "hamb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "MCU temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "tmcu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "MCU voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vmcu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Solar cell voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vsrc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Supercap voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_site",
     "groupBy": [
      { "params": [ "site" ], "type": "tag" }
     ],
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "vcap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Status bits",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "measurement": "monitoring",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&128 / 128" ], "type": "math" },
       { "params": [ "GPS backup" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&64 / 64" ], "type": "math" },
       { "params": [ "Accelerometer" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&32 / 32" ], "type": "math" },
       { "params": [ "LSE status" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&16 / 16" ], "type": "math" },
       { "params": [ "LSI status" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&8 / 8" ], "type": "math" },
       { "params": [ "Moving flag" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&4 /4" ], "type": "math" },
       { "params": [ "Alarm flag" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&3 / 3" ], "type": "math" },
       { "params": [ "Tracker mode" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Reset flags",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "measurement": "global",
     "select": [
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&128 / 128" ], "type": "math" },
       { "params": [ "Low power" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&64 / 64" ], "type": "math" },
       { "params": [ "Window watchdog" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&32 / 32" ], "type": "math" },
       { "params": [ "Independent watchdog" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&16 / 16" ], "type": "math" },
       { "params": [ "Software" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&8 / 8" ], "type": "math" },
       { "params": [ "POR" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&4 /4" ], "type": "math" },
       { "params": [ "Pin" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&2 / 2" ], "type": "math" },
       { "params": [ "Option bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "reset_flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "&1 / 1" ], "type": "math" },
       { "params": [ "Firewall" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  },
  {
   "title": "Error stack",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "hex0x" } },
   "targets": [
    {
     "measurement": "global",
     "select": [
      [
       { "params": [ "error" ], "type": "field" },
       { "params": [ "Error code" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "asset", "operator": "=~", "value": "/^$asset$/" }
     ]
    }
   ]
  }
 ]
}